version: '3.8'
name: product-crud
services:
    api:
        container_name: product-api
        image: products-crud-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80