version: '3.8'
name: calculator
services:
    api:
        container_name: calculator-web-api
        image: calculator-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80